# Generated by Django 3.2.2 on 2021-05-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parliament1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("date_born", models.DateField(blank=True, null=True)),
                ("place_born", models.CharField(blank=True, max_length=50, null=True)),
                ("profession", models.CharField(blank=True, max_length=80, null=True)),
                ("lang", models.CharField(blank=True, max_length=70, null=True)),
                ("party", models.CharField(blank=True, max_length=80, null=True)),
                ("email", models.CharField(blank=True, max_length=80, null=True)),
                ("url", models.TextField(blank=True, max_length=15, null=True)),
                ("pp", models.TextField(blank=True, max_length=10, null=True)),
                ("dob", models.TextField(blank=True, max_length=15, null=True)),
            ],
            options={
                "db_table": "Parliament1",
            },
        ),
    ]
