# Generated by Django 3.2.2 on 2021-05-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0002_parliament1_education"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="parliament1",
            table="parliament",
        ),
    ]
